from queueNode import QueueNode
from queueArray import QueueArray

nodeQueue = QueueNode()
print("QueueNode")
print("isEmpty: " + nodeQueue.isEmpty())
print("enqueue(1)")
nodeQueue.enqueue(1)
print("enqueue(2)")
nodeQueue.enqueue(2)
print("enqueue(3)")
nodeQueue.enqueue(3)
print(nodeQueue)
print("length: " + nodeQueue.getLength())
print("isEmpty: " + nodeQueue.isEmpty())
print("front: " + nodeQueue.frontValue())
print("dequeue: " + nodeQueue.dequeue())
print("dequeue: " + nodeQueue.dequeue())
print("dequeue: " + nodeQueue.dequeue())
print("isEmpty: " + nodeQueue.isEmpty())

arrayQueue = QueueArray(5)
print("QueueArray")
print("isEmpty: " + arrayQueue.isEmpty())
print("enqueue(1)")
arrayQueue.enqueue(1)
print("enqueue(2)")
arrayQueue.enqueue(2)
print("enqueue(3)")
arrayQueue.enqueue(3)
print(arrayQueue)
print("length: " + arrayQueue.getLength())
print("isEmpty: " + arrayQueue.isEmpty())
print("front: " + arrayQueue.frontValue())
print("dequeue: " + arrayQueue.dequeue())
print("dequeue: " + arrayQueue.dequeue())
print("dequeue: " + arrayQueue.dequeue())
print("isEmpty: " + arrayQueue.isEmpty())